import type { Indicator } from './types'

/** 指标定义的分文件组织；所有调用方统一读取 indicators.ts 的 INDICATORS。 */
function define(id: string, name: string, category: Indicator['category'], note: string,
  options: Partial<Indicator> = {}): Indicator {
  return {
    id, nameZh: name, nameShort: name, category, unit: '%', frequency: 'month',
    valueType: 'yoy', seasonalAdj: false, decimals: 1, isHeadline: false, tier: 'P1',
    note, ...options,
  }
}

export const TRADE_PARTNERS = [
  { code: 'us', name: '美国' }, { code: 'eu', name: '欧盟' },
  { code: 'asean', name: '东盟' }, { code: 'jp', name: '日本' }, { code: 'kr', name: '韩国' },
] as const

export const RETAIL_ITEMS = [
  { code: 'food', name: '粮油食品' }, { code: 'clothing', name: '服装鞋帽针纺织品' },
  { code: 'auto', name: '汽车' }, { code: 'appliance', name: '家用电器和音像器材' },
  { code: 'cosmetics', name: '化妆品' },
] as const

export const PROVINCES = [
  { code: 'bj', name: '北京' }, { code: 'tj', name: '天津' }, { code: 'he', name: '河北' },
  { code: 'sx', name: '山西' }, { code: 'nm', name: '内蒙古' }, { code: 'ln', name: '辽宁' },
  { code: 'jl', name: '吉林' }, { code: 'hl', name: '黑龙江' }, { code: 'sh', name: '上海' },
  { code: 'js', name: '江苏' }, { code: 'zj', name: '浙江' }, { code: 'ah', name: '安徽' },
  { code: 'fj', name: '福建' }, { code: 'jx', name: '江西' }, { code: 'sd', name: '山东' },
  { code: 'ha', name: '河南' }, { code: 'hb', name: '湖北' }, { code: 'hn', name: '湖南' },
  { code: 'gd', name: '广东' }, { code: 'gx', name: '广西' }, { code: 'hi', name: '海南' },
  { code: 'cq', name: '重庆' }, { code: 'sc', name: '四川' }, { code: 'gz', name: '贵州' },
  { code: 'yn', name: '云南' }, { code: 'xz', name: '西藏' }, { code: 'sn', name: '陕西' },
  { code: 'gs', name: '甘肃' }, { code: 'qh', name: '青海' }, { code: 'nx', name: '宁夏' },
  { code: 'xj', name: '新疆' },
] as const

const cumulative = { valueType: 'cumulative_yoy' as const }
const quarter = { frequency: 'quarter' as const }
const dailyRate = { frequency: 'day' as const, valueType: 'level' as const, decimals: 2 }

export const EXPANDED_INDICATORS: Indicator[] = [
  define('cn.fai.mfg_cum_yoy', '制造业投资累计同比', 'demand',
    '固定资产投资中制造业投资的年内累计同比，每年重新起算，1—2 月合并发布。与房地产开发投资等分项统计范围不同，不能加总增速。', cumulative),
  define('cn.fai.infra_cum_yoy', '基建投资累计同比', 'demand',
    '基础设施投资（不含电力、热力、燃气及水生产和供应业）的年内累计同比，每年重新起算，1—2 月合并发布。不是全口径基建投资。', cumulative),
  ...RETAIL_ITEMS.map(({ code, name }) => define(`cn.retail.${code}_yoy`, `${name}零售额当月同比`, 'demand',
    `限额以上单位${name}类商品零售额的当月同比，非全部社会消费品零售总额口径。1—2 月合并发布；示例类别只用于分项浏览，并非完整分类，不可将增速直接加总。`)),
  ...TRADE_PARTNERS.flatMap(({ code, name }) => ['export', 'import'].map((flow) =>
    define(`cn.trade.${code}_${flow}`, `${flow === 'export' ? '对' : '自'}${name}${flow === 'export' ? '出口' : '进口'}金额`, 'external',
      `按美元计价的当月货物${flow === 'export' ? '出口' : '进口'}金额，伙伴为${name}，不是累计金额。国别/地区仅提供演示选项，不构成完整、互斥的贸易伙伴全集。`,
      { unit: '亿美元', valueType: 'level', region: name }))),
  define('cn.pmi.caixin_mfg', '财新制造业 PMI', 'sentiment',
    '财新中国制造业采购经理指数，采用不同于官方制造业 PMI 的调查样本。经季节调整，50 为荣枯线；本应用数值完全合成，没有引入付费终端或复制真实财新数据。',
    { unit: '点', valueType: 'index', seasonalAdj: true }),
  define('cn.pmi.caixin_services', '财新服务业 PMI', 'sentiment',
    '财新中国服务业商务活动指数，服务业调查范围与官方非制造业（包含建筑业）不同。经季节调整，50 为荣枯线；数值完全合成，不是真实财新统计。',
    { unit: '点', valueType: 'index', seasonalAdj: true }),
  define('cn.services.yoy', '服务业生产指数同比', 'growth',
    '服务业生产指数扣除价格因素后的当月同比，反映服务业产出变化；1—2 月合并发布，不是服务业增加值累计增速。'),
  define('cn.power.generation', '发电量当月值', 'growth',
    '规模以上工业企业发电量，单位为亿千瓦时，非全社会所有发电设备产量。1—2 月合并发布，合并期间数值为两个月合计。',
    { unit: '亿千瓦时', valueType: 'level', decimals: 0 }),
  define('cn.power.generation_yoy', '发电量当月同比', 'growth',
    '规模以上工业企业发电量的可比口径当月同比；1—2 月合并发布，非年内累计增速。'),
  define('cn.power.consumption', '全社会用电量当月值', 'growth',
    '全社会各行业与居民生活当月用电量，单位为亿千瓦时；不是规模以上工业发电量，不能据两者差值推断供需缺口。',
    { unit: '亿千瓦时', valueType: 'level', decimals: 0 }),
  define('cn.power.consumption_yoy', '全社会用电量当月同比', 'growth',
    '全社会用电量当月同比，非年内累计同比。示例值独立合成，不从相邻月份的用电量反推。'),
  define('cn.income.disposable_cum_yoy', '居民人均可支配收入累计同比', 'demand',
    '全国居民人均可支配收入年初至当季累计名义同比，未扣除价格因素，不是实际增长率或当季同比。',
    { ...cumulative, ...quarter }),
  define('cn.income.consumption_cum_yoy', '居民人均消费支出累计同比', 'demand',
    '全国居民人均消费支出年初至当季累计名义同比，未扣除价格因素，非社会消费品零售总额口径。',
    { ...cumulative, ...quarter }),
  define('cn.income.disposable', '居民人均可支配收入累计值', 'demand',
    '全国居民年初至当季的人均可支配收入名义累计金额，单位为元，非当季收入；累计值之差不直接等同于可比的当季人均收入。',
    { ...quarter, unit: '元', valueType: 'cumulative', decimals: 0 }),
  define('cn.income.consumption', '居民人均消费支出累计值', 'demand',
    '全国居民年初至当季的人均消费支出名义累计金额，单位为元，非当季支出、非社会消费品零售额；跨年重新起算。',
    { ...quarter, unit: '元', valueType: 'cumulative', decimals: 0 }),
  define('cn.fiscal.fund_revenue_cum_yoy', '政府性基金收入累计同比', 'fiscal',
    '全国政府性基金预算收入的年内累计同比，非一般公共预算收入；1—2 月合并发布，跨年重新起算。', cumulative),
  define('cn.fiscal.land_revenue_cum_yoy', '土地出让收入累计同比', 'fiscal',
    '地方政府性基金预算收入中国有土地使用权出让收入的年内累计同比；它是政府性基金收入的组成部分，不可重复加总。1—2 月合并发布。', cumulative),
  define('cn.gdp.nominal_yoy', '名义 GDP 当季同比', 'growth',
    '现价 GDP 当季名义同比，包含价格变化，不能替代按不变价格计算的实际 GDP 同比；作为示例 GDP 平减指数的输入。', quarter),
  define('cn.gdp.deflator_yoy', 'GDP 平减指数同比变化', 'price',
    '示例计算值：[(1 + 名义 GDP 当季同比 / 100) / (1 + 实际 GDP 当季同比 / 100) − 1] × 100。表示隐含价格指数同比变化，非 CPI、非价格指数点位；输入均为假数据。',
    { ...quarter, isDerived: true }),
  define('cn.bond.gov_1y', '国债收益率 1 年期', 'money',
    '中国国债 1 年期到期收益率，年化百分比，非票面利率。示例采用周一至周五日期，未模拟法定节假日，曲线节点不能替代具体债券报价。', dailyRate),
  define('cn.bond.gov_10y', '国债收益率 10 年期', 'money',
    '中国国债 10 年期到期收益率，年化百分比，非票面利率；周一至周五的合成曲线节点，不代表真实交易报价。', dailyRate),
  define('us.bond.gov_10y', '美国国债收益率 10 年期', 'money',
    '美国国债 10 年期到期收益率的合成日度示例，年化百分比。日期按同一周一至周五演示日历对齐，不模拟两地交易日、收盘时刻或时区差异。', { ...dailyRate, region: '美国' }),
  define('cn.bond.cn_us_spread', '中美 10 年期国债利差', 'money',
    '示例计算值：(中国 10 年期国债收益率 − 美国 10 年期国债收益率) × 100，单位为基点，1 基点 = 0.01 个百分点。按相同示例日期计算；不模拟两地收盘时间差，缺少任一输入时留空。',
    { frequency: 'day', unit: '基点', valueType: 'level', decimals: 1, isDerived: true }),
  define('cn.rail.freight_yoy', '铁路货运量当月同比', 'growth',
    '铁路货物运输量当月同比，非周转量或货运收入。这里用作示例克强指数的输入，不代表真实铁路统计。'),
  define('cn.loan.medium_long_yoy', '中长期人民币贷款余额同比', 'money',
    '金融机构中长期人民币贷款月末余额同比，非当月新增贷款金额；这里用作示例克强指数的输入。'),
  define('cn.population.total', '年末人口总量', 'society',
    '中国大陆年末人口总量，单位为万人，范围为大陆 31 个省、自治区、直辖市人口，不包括港澳台居民和居住在大陆的外籍人员；非劳动年龄人口。',
    { tier: 'P2', frequency: 'year', unit: '万人', valueType: 'level', decimals: 0 }),
  define('cn.population.urbanization', '常住人口城镇化率', 'society',
    '年末城镇常住人口占总人口的比重，非户籍人口城镇化率；单位为百分比，年度值不是月度调查结果。',
    { tier: 'P2', frequency: 'year', valueType: 'level', decimals: 2 }),
  define('cn.income.gini', '居民收入基尼系数', 'society',
    '全国居民收入分配的年度基尼系数，采用 0–1 尺度，不是百分数；数值越高表示收入分配差异越大。',
    { tier: 'P2', frequency: 'year', unit: '系数', valueType: 'level', decimals: 3 }),
  ...[
    { code: 'current', name: '经常账户差额', note: '涵盖货物、服务、初次收入和二次收入' },
    { code: 'capital', name: '资本账户差额', note: '涵盖资本转移和非生产非金融资产交易，非金融账户' },
    { code: 'financial', name: '金融账户差额', note: '包括储备资产；采用资产净获得减负债净发生的差额方向，正值表示对外净融出' },
  ].map(({ code, name, note }) => define(`cn.bop.${code}`, `国际收支${name}`, 'external',
      `按国际收支平衡表口径的当季${name}，${note}，单位为亿美元。经常账户与资本账户正值为贷方净额；金融账户符号方向不同，不能简单加总。${code === 'capital' ? '' : '示例计算值：对应账户的四个合成分项之和。'}`,
      { tier: 'P2', ...quarter, unit: '亿美元', valueType: 'level', isDerived: code !== 'capital' })),
  ...[
    { code: 'goods', name: '货物差额', note: '按国际收支口径调整后的货物贷方减借方，不能与海关货物贸易差额直接互换' },
    { code: 'services', name: '服务差额', note: '服务贸易贷方减借方，不包括初次与二次收入' },
    { code: 'primary_income', name: '初次收入差额', note: '雇员报酬、投资收益等初次收入的贷方减借方' },
    { code: 'secondary_income', name: '二次收入差额', note: '经常转移等二次收入的贷方减借方，非资本转移' },
    { code: 'direct_investment', name: '直接投资差额', note: '采用资产净获得减负债净发生方向，正值表示净对外投资' },
    { code: 'portfolio_investment', name: '证券投资差额', note: '采用资产净获得减负债净发生方向，非证券成交金额' },
    { code: 'other_financial', name: '其他金融投资差额', note: '演示合并其他投资与金融衍生工具，采用资产净获得减负债净发生方向' },
    { code: 'reserve_assets', name: '储备资产净获得', note: '金融账户中的储备资产净获得，正值表示增加；非外汇储备期末余额的简单差值' },
  ].map(({ code, name, note }) => define(`cn.bop.${code}`, `国际收支${name}`, 'external',
    `国际收支当季流量，${note}，单位为亿美元。合成示例，非年内累计值。`,
    { tier: 'P2', ...quarter, unit: '亿美元', valueType: 'level' })),
  define('cn.bop.errors', '国际收支净误差与遗漏', 'external',
    '示例计算值：金融账户差额 − 经常账户差额 − 资本账户差额，使“经常 + 资本 − 金融 + 净误差与遗漏 = 0”。真实净误差与遗漏用于平衡实际统计差异，此处仅演示记账方向与恒等式，不是实际误差估计。',
    { tier: 'P2', ...quarter, unit: '亿美元', valueType: 'level', isDerived: true }),
  define('cn.external_debt.balance', '全口径外债余额', 'external',
    '季度末全口径外债余额，包含本外币外债，按美元折算、单位为亿美元；是余额，不是当季新增外债，也不能直接用外汇储备减去得到净外债。',
    { tier: 'P2', ...quarter, unit: '亿美元', valueType: 'level', decimals: 2 }),
  ...PROVINCES.map(({ code, name }) => define(`cn.region.${code}.gdp_cum_yoy`, `${name} GDP 累计同比`, 'growth',
    `${name}地区生产总值按不变价格计算的年初至当季累计同比，非当季同比，不与全国当季 GDP 口径混画。跨省增速不可加总；省级观测均为合成示例，覆盖大陆 31 个省级地区，不包含港澳台。`,
    { tier: 'P2', region: name, ...quarter, ...cumulative })),
  define('cn.keqiang.growth', '克强指数（示例加权增速）', 'growth',
    '示例计算值：0.40 × 全社会用电量当月同比 + 0.25 × 铁路货运量当月同比 + 0.35 × 中长期人民币贷款余额同比。这只是演示权重的合成增长指标，克强指数没有统一官方口径；非 GDP、非标准指数点位，输入均为假数据。',
    { tier: 'P2', isDerived: true }),
]
