// ============================================
// 根布局（Root Layout）：整个应用的外壳
// ============================================
//
// 这个文件相当于 Vite 项目里的 index.html，但性质完全不同：
//
//   Vite 的 index.html 是一个静态文件，React 碰不到它；
//   layout.tsx 是一个 React 组件，能跑 JS、能引样式、能读数据。
//
// 一一对照（左：04-React_learn/index.html，右：本文件）：
//
//   <html lang="zh-CN">             →   <html lang="en">
//   <body>                          →   <body className={...}>
//   <div id="root"></div>           →   {children}
//   <head> 里的 <title>             →   export const metadata
//   <script src="/src/main.jsx">    →   不需要，Next.js 自己接管
//
// App Router 里根本没有 index.html，<html> 和 <body> 这两个标签
// 必须由某个组件吐出来 —— 就是这个文件。官方文档的原话是：
// app 目录「必须」包含一个根布局，且根布局「必须」定义 <html> 和 <body>。

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// 全局样式在这里引入：layout 是所有页面共享的入口，所以引一次就全站生效。
import "./globals.css";

// ============================================
// 字体：构建时下载到本地，不进浏览器请求 Google
// ============================================
//
// next/font 会在构建时把字体文件抓下来自己托管，所以浏览器不会去请求
// Google 的服务器（国内能正常加载就是这个原因）。
//
// 注意这里存下来的不是字体本身，而是两个 CSS 变量名，
// 真正把它们挂到页面上，靠的是文件末尾 <body> 的 className。

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ============================================
// metadata：自动生成 <head> 里的标签
// ============================================
//
// 不要自己手写 <head><title>...</title></head> —— 官方明确说根布局里
// 不该手动加 <head> 标签，要用 Metadata API，它负责去重、流式输出这些细节。
//
// 实测：/、/basics、/blog/1 三个路由的 <title> 都是下面这个值，
// 因为 metadata 写在 layout 里，所以全站生效。
// 目前还是脚手架的默认值，想改站名改这里。

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ============================================
// 布局组件本身
// ============================================
//
// 这个文件没有 'use client'，所以它是 Server Component：
// <html>/<body> 在服务器上生成好再发给浏览器（SSR）。
// 这也是为什么它不能写 useState / onClick —— 那些是浏览器才有的东西。
//
// ---------- 先说清楚：这个函数从来不是你调用的 ----------
//
// 全项目搜不到任何一行代码调用或 import 它，调用者是 Next.js 自己。
// 它靠「文件名」认出这个文件（layout.tsx 是特殊文件名），
// 编译时把它编进每一条路由的模块图，请求到了再调用它。
//
// ---------- 这行声明的每个部分 ----------
//
//   export       ESM 导出，让外部能 import 它
//   default      默认导出 —— Next.js 取的就是它，这个位置不能少
//   function     函数声明（不是箭头函数）
//   RootLayout   函数名 —— 对 Next.js 完全无意义，改成 Foo 照样跑
//
// 换句话说：约定在【文件名】上，不在【函数名】上。
//
// ---------- 它只接收一个参数 ----------
//
// 运行时 Next.js 是这样调用它的：
//
//   RootLayout({ children: <页面组件 /> })
//
// 就一个参数：一个 props 对象。下面的 { children } 只是把它拆开写。
// 所以下面三种写法完全等价：
//
//   1. function RootLayout({ children }: Readonly<{ children: React.ReactNode }>)
//   2. function RootLayout(props: Readonly<{ children: React.ReactNode }>)
//   3. function RootLayout({ children }: { children: React.ReactNode })

export default function RootLayout({
  // children 由 Next.js 自动传入，内容就是「当前路由匹配到的页面」：
  //   访问 /        → 塞进来 app/page.tsx
  //   访问 /basics  → 塞进来 app/basics/page.tsx
  //   访问 /blog/1  → 塞进来 app/blog/[id]/page.tsx
  //
  // 注意 children 不是关键字，只是个约定俗成的 prop 名。它之所以特殊，
  // 是因为 JSX 里标签之间的内容会自动变成它：
  //   <Counter>你好</Counter>   等价于   <Counter children="你好" />
  // Next.js 就是用后一种方式把页面塞进来的。
  children,

  // ↑ 上面这个 { } 和下面这个 { } 不是一回事 —— 这是最容易卡住的地方：
  //
  //     { children, }                   ← JS 的【解构】：运行时真的去对象里取属性
  //     Readonly<{ children: ... }>     ← TS 的【类型】：编译后一行不剩
  //
  // 一个是值、一个是类型，分属两种语言，连分隔符都不同
  // （解构里用逗号，类型里用分号）。有点像 C 里同一个 { } 既能是代码块
  // 又能是初始化列表，得靠上下文判断。
}: Readonly<{
  // Readonly<T> 是 TS 内置工具类型，把 T 的属性全变成只读。
  // 但它实际挡不住多少东西，实测三种情况：
  //
  //   props.children = 'x'     → error TS2540: Cannot assign to 'children'
  //                              because it is a read-only property.
  //   解构出来的 children 再赋值 → 不报错（解构是拷贝，局部变量不受保护）
  //   不加 Readonly 时上一条     → 不报错
  //
  // 所以它在这里主要是「表达意图」：这是框架传给你的，别改。
  // 另外它是【浅】的 —— 只保护这一层属性，嵌套对象照样能改。

  children: React.ReactNode;

  // React.ReactNode = React 画得出来的任何东西。@types/react 里的定义是：
  //   ReactElement | string | number | bigint | Iterable<ReactNode>
  //   | ReactPortal | boolean | null | undefined
  //
  // 没 import React 也能写 React.ReactNode，是因为 @types/react 里有一行
  // `export as namespace React;`（UMD 全局声明），让 React 作为【类型】
  // 命名空间全局可用。注意只在类型位置能用 —— 真去调 React.createElement()
  // 会报 "refers to a UMD global"。
  // 等价写法：import type { ReactNode } from 'react'
}>) {
  return (
    <html lang="en">
      {/* 这个标签是手写的 JSX，不是某个模板生成的。
          想做中文站点就改成 lang="zh-CN"（现在还是脚手架默认的 en）。 */}

      {/* body 上拼了三个 class：两个字体 CSS 变量 + antialiased（抗锯齿）。
          实测渲染出来的结果是：
            class="geist_a71539c9-module__T19VSG__variable
                   geist_mono_8d43a2aa-module__8Li5zG__variable antialiased" */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {children} 就是「页面的位置」—— 换路由时只有这一块被替换，
            外面的 <html>/<body> 不动。 */}
        {children}
      </body>
    </html>
  );
}

// ============================================
// 两个容易忽略、但很重要的性质
// ============================================
//
// 1. layout 不随导航重新渲染
//
//    官方文档原话："Layouts do not rerender. They can be cached and reused
//    to avoid unnecessary computation when navigating between pages."
//
//    这一点和「把导航栏抽成组件、每个 page 里 import 一次」有本质区别：
//
//      写在每个 page 里  → 每次跳页都重新挂载，组件内部 state 清零
//      写在 layout 里    → 跳页时实例原地保留，只有 {children} 被换掉
//
//    所以导航栏、侧边栏、Footer、全局 Provider 都应该放这里。
//
//    C/C++ 类比：layout 像静态存储期的对象（程序活多久它活多久），
//                page 像每次调用重新构造的局部对象（导航一次重建一次）。
//
//    注意：要看到这个效果，跳转必须用 <Link>（客户端跳转）。
//    用普通 <a> 标签会整页重新加载，layout 被销毁重建，效果就看不到了。
//
// 2. 可以嵌套
//
//    app/ 下每个目录都可以有自己的 layout.tsx，会一层层套起来。
//    目前这个项目只有这一个。以后加 app/blog/layout.tsx，
//    那 /blog/* 的层级就是：RootLayout → BlogLayout → page。
